<div style="width: 250px; margin: 0 auto;">

    <form id="frm_signin" class="form-signin" role="form">
        <h2 class="form-signin-heading">Acessar</h2>
        <input type="email" id="email" class="form-control" placeholder="E-mail" required autofocus>
        <input type="password" id="senha" class="form-control" placeholder="Senha" required>
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Lembrar-me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
    </form>

</div>